# Generated by Django 4.0.4 on 2022-07-10 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('synopsis', models.TextField(verbose_name='خلاصه داستان')),
                ('actors', models.CharField(max_length=255, verbose_name='بازیگران')),
                ('genre', models.CharField(max_length=255, verbose_name='ژانر')),
                ('duration', models.IntegerField(verbose_name='مدت زمان')),
            ],
            options={
                'verbose_name': 'فیلم',
                'verbose_name_plural': 'فیلم ها',
            },
        ),
    ]
